# Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Версия приложения (SemVer). Переопределяется в GitLab CI из тега vX.Y.Z.
VERSION_MAJOR=0
VERSION_MINOR=1
VERSION_PATCH=0

# GitLab CI переопределяет через -PVERSION_NAME=... и -PVERSION_CODE=...
VERSION_NAME=0.1.0
VERSION_CODE=100
# AndroidX обязателен (AGP 8 требует явного включения)
android.useAndroidX=true
